---
title: "georefar"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejemplo de Usos

Para cargar la librería:
```{r}
library(georefar)
library(tidyverse)
```

Para obtener un listado de provincias:
```{r}
prov <- get_provincias(orden = "id", max = 5)
```

Para obtener un listado de departamentos:
```{r}
get_departamentos(provincia = "Corrientes", orden = "id", max = 5)
```

Para obtener un listado de municipios:
```{r}
get_municipios(provincia = "Santa Fe", max = 5)
```

Para obtener un listado de localidades:
```{r}
get_localidades(provincia = "Chubut", max = 5)
```

Para obtener la ubicacion de un punto (reverse-geocoding):
```{r}
get_ubicacion(-31.6515236,-64.4358794)
```

```{r}
BSAS <- get_geo(geo =  "BUENOS AIRES") 

fina2020 <- st_read("https://github.com/juanchiem/agro_data/raw/master/Sitios_experimentales_2020_Juan.kml")
nc_centers <- st_centroid(fina2020)
bbox <- expand_bbox(st_bbox(nc_centers), X = 0, Y = 150000)

library(basemapR)

BSAS %>%
  ggplot() +
  base_map(bbox, increase_zoom = 2, basemap = 'google-terrain') +
  geom_sf(alpha = 0.1, color=alpha("red",0.1) , show.legend = FALSE)+
  geom_sf(data = fina2020[1], show.legend = FALSE)+
  coord_sf(xlim= c(-61, -57),ylim= c(-39,-36.5))+
  theme_void()
  geom_sf_label(aes(label = coddepto), label.padding = unit(1, "mm"))
```

